# Generated by Django 4.0.2 on 2022-02-15 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KorzinaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('product', models.JSONField()),
            ],
        ),
    ]
