# Generated by Django 4.0.2 on 2022-02-15 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all', '0002_korzinamodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='korzinamodel',
            name='count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='korzinamodel',
            name='price',
            field=models.FloatField(default=2),
            preserve_default=False,
        ),
    ]
