# Generated by Django 4.0.2 on 2022-02-15 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all', '0003_korzinamodel_count_korzinamodel_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='korzinamodel',
            name='product',
            field=models.CharField(max_length=255),
        ),
    ]
