# Generated by Django 4.0.2 on 2022-03-20 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all', '0007_alter_ordermodel_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='order',
            field=models.CharField(choices=[('Kutilmoqda', 'Kutilmoqda'), ('BekorQilindi', 'BekorQilindi'), ('Tasdiqlandi', 'Tasdiqlandi'), ('Yuborildi', 'Yuborildi'), ('Yetkazildi', 'Yetkazildi')], default='Kutilmoqda', max_length=50),
        ),
    ]
