# Generated by Django 4.0.2 on 2022-03-21 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all', '0008_alter_ordermodel_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='kuryer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='order',
            field=models.CharField(choices=[('Kutilmoqda', 'Kutilmoqda'), ('Bekor Qilindi', 'Bekor Qilindi'), ('Tasdiqlandi', 'Tasdiqlandi'), ('Yuborildi', 'Yuborildi'), ('Yetkazildi', 'Yetkazildi')], default='Kutilmoqda', max_length=50),
        ),
    ]
