# Generated by Django 4.0.5 on 2022-11-15 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('all', '0009_ordermodel_date_ordermodel_kuryer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='image',
        ),
    ]
