# Generated by Django 4.1.7 on 2023-04-05 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all', '0010_remove_productmodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='image',
            field=models.TextField(default='sadf'),
            preserve_default=False,
        ),
    ]
