# Generated by Django 4.2.4 on 2023-08-20 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all', '0011_productmodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
